#ubuntu 16.04 wordpress 4.5

Vagrant.configure("2") do |config|
    #config.vm.box = "ubuntu/xenial64"
    config.vm.box = "ubuntu/trusty64"
    config.vm.provision :shell, path: "bootstrap.sh"
    config.vm.network :forwarded_port, guest: 80, host: 8080
    config.vm.network :forwarded_port, guest: 8081, host: 8081
    config.vm.network :forwarded_port, guest: 8082, host: 8082
    config.vm.synced_folder "./", "/home/app", group: "www-data"
end
