Vagrant.configure("2") do |config|
    config.vm.provision :shell, inline: "echo Multi-Machine Setup"

    config.vm.define "webserver", primary: true do |webserver|
        config.vm.box = "ubuntu/trusty64"
        config.vm.provision :shell, path: "bootstrap.webserver.sh"
        config.vm.network :forwarded_port, guest: 8080, host: 8080
        config.vm.synced_folder "./", "/home/app"
    end

    config.vm.define "compiler", autostart: false do |compiler|
        config.vm.box = "ubuntu/trusty64"
        config.vm.provision :shell, path: "bootstrap.compiler.sh"
        config.vm.synced_folder "./", "/home/app"
    end
end
